// export const PROFILE_NAME_SET = 'PROFILE_NAME_SET';
// export const PROFILE_NAME_TOGGLE_DISABLED = 'PROFILE_NAME_TOGGLE_DISABLED';
// export const PROFILE_EMAIL_SET = 'PROFILE_EMAIL_SET';
// export const PROFILE_EMAIL_TOGGLE_DISABLED = 'PROFILE_EMAIL_TOGGLE_DISABLED';
// export const PROFILE_PASSWORD_SET = 'PROFILE_PASSWORD_SET';
// export const PROFILE_PASSWORD_TOGGLE_DISABLED = 'PROFILE_PASSWORD_TOGGLE_DISABLED';