export const FEED_WS_CONNECTION_START = 'FEED_WS_CONNECTION_START';
export const FEED_WS_CONNECTION_STOP = 'FEED_WS_CONNECTION_STOP';

export const ORDERS_WS_CONNECTION_START = 'ORDERS_WS_CONNECTION_START';
export const ORDERS_WS_CONNECTION_STOP = 'ORDERS_WS_CONNECTION_STOP';